#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class Iface:
  def loginWithIdentityCredentialForCertificate(self, cr1, cr2, flag1, ip, comname, val1, cr5):
    """
    Parameters:
     - cr1
     - cr2
     - flag1
     - ip
     - comname
     - val1
     - cr5
    """
    pass

  def loginWithIdentityCredentialForCertificate2(self, cr1, cr2, flag1, ip, comname, val1, cr5):
    """
    Parameters:
     - cr1
     - cr2
     - flag1
     - ip
     - comname
     - val1
     - cr5
    """
    pass


class Client(Iface):
  def __init__(self, iprot, oprot=None):
    self._iprot = self._oprot = iprot
    if oprot is not None:
      self._oprot = oprot
    self._seqid = 0

  def loginWithIdentityCredentialForCertificate(self, cr1, cr2, flag1, ip, comname, val1, cr5):
    """
    Parameters:
     - cr1
     - cr2
     - flag1
     - ip
     - comname
     - val1
     - cr5
    """
    self.send_loginWithIdentityCredentialForCertificate(cr1, cr2, flag1, ip, comname, val1, cr5)
    return self.recv_loginWithIdentityCredentialForCertificate()

  def send_loginWithIdentityCredentialForCertificate(self, cr1, cr2, flag1, ip, comname, val1, cr5):
    self._oprot.writeMessageBegin('loginWithIdentityCredentialForCertificate', TMessageType.CALL, self._seqid)
    args = loginWithIdentityCredentialForCertificate_args()
    args.cr1 = cr1
    args.cr2 = cr2
    args.flag1 = flag1
    args.ip = ip
    args.comname = comname
    args.val1 = val1
    args.cr5 = cr5
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_loginWithIdentityCredentialForCertificate(self, ):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = loginWithIdentityCredentialForCertificate_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success is not None:
      return result.success
    raise TApplicationException(TApplicationException.MISSING_RESULT, "loginWithIdentityCredentialForCertificate failed: unknown result");

  def loginWithIdentityCredentialForCertificate2(self, cr1, cr2, flag1, ip, comname, val1, cr5):
    """
    Parameters:
     - cr1
     - cr2
     - flag1
     - ip
     - comname
     - val1
     - cr5
    """
    self.send_loginWithIdentityCredentialForCertificate2(cr1, cr2, flag1, ip, comname, val1, cr5)
    return self.recv_loginWithIdentityCredentialForCertificate2()

  def send_loginWithIdentityCredentialForCertificate2(self, cr1, cr2, flag1, ip, comname, val1, cr5):
    self._oprot.writeMessageBegin('loginWithIdentityCredentialForCertificate2', TMessageType.CALL, self._seqid)
    args = loginWithIdentityCredentialForCertificate2_args()
    args.cr1 = cr1
    args.cr2 = cr2
    args.flag1 = flag1
    args.ip = ip
    args.comname = comname
    args.val1 = val1
    args.cr5 = cr5
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_loginWithIdentityCredentialForCertificate2(self, ):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = loginWithIdentityCredentialForCertificate2_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success is not None:
      return result.success
    raise TApplicationException(TApplicationException.MISSING_RESULT, "loginWithIdentityCredentialForCertificate2 failed: unknown result");


class Processor(Iface, TProcessor):
  def __init__(self, handler):
    self._handler = handler
    self._processMap = {}
    self._processMap["loginWithIdentityCredentialForCertificate"] = Processor.process_loginWithIdentityCredentialForCertificate
    self._processMap["loginWithIdentityCredentialForCertificate2"] = Processor.process_loginWithIdentityCredentialForCertificate2

  def process(self, iprot, oprot):
    (name, type, seqid) = iprot.readMessageBegin()
    if name not in self._processMap:
      iprot.skip(TType.STRUCT)
      iprot.readMessageEnd()
      x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
      oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
      x.write(oprot)
      oprot.writeMessageEnd()
      oprot.trans.flush()
      return
    else:
      self._processMap[name](self, seqid, iprot, oprot)
    return True

  def process_loginWithIdentityCredentialForCertificate(self, seqid, iprot, oprot):
    args = loginWithIdentityCredentialForCertificate_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = loginWithIdentityCredentialForCertificate_result()
    result.success = self._handler.loginWithIdentityCredentialForCertificate(args.cr1, args.cr2, args.flag1, args.ip, args.comname, args.val1, args.cr5)
    oprot.writeMessageBegin("loginWithIdentityCredentialForCertificate", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()

  def process_loginWithIdentityCredentialForCertificate2(self, seqid, iprot, oprot):
    args = loginWithIdentityCredentialForCertificate2_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = loginWithIdentityCredentialForCertificate2_result()
    result.success = self._handler.loginWithIdentityCredentialForCertificate2(args.cr1, args.cr2, args.flag1, args.ip, args.comname, args.val1, args.cr5)
    oprot.writeMessageBegin("loginWithIdentityCredentialForCertificate2", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()


# HELPER FUNCTIONS AND STRUCTURES

class loginWithIdentityCredentialForCertificate_args:
  """
  Attributes:
   - cr1
   - cr2
   - flag1
   - ip
   - comname
   - val1
   - cr5
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'cr1', None, None, ), # 1
    (2, TType.STRING, 'cr2', None, None, ), # 2
    (3, TType.BOOL, 'flag1', None, None, ), # 3
    (4, TType.STRING, 'ip', None, None, ), # 4
    (5, TType.STRING, 'comname', None, None, ), # 5
    (6, TType.I32, 'val1', None, None, ), # 6
    (7, TType.STRING, 'cr5', None, None, ), # 7
  )

  def __init__(self, cr1=None, cr2=None, flag1=None, ip=None, comname=None, val1=None, cr5=None,):
    self.cr1 = cr1
    self.cr2 = cr2
    self.flag1 = flag1
    self.ip = ip
    self.comname = comname
    self.val1 = val1
    self.cr5 = cr5

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.cr1 = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.cr2 = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.BOOL:
          self.flag1 = iprot.readBool();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.ip = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.STRING:
          self.comname = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.I32:
          self.val1 = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.STRING:
          self.cr5 = iprot.readString();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('loginWithIdentityCredentialForCertificate_args')
    if self.cr1 is not None:
      oprot.writeFieldBegin('cr1', TType.STRING, 1)
      oprot.writeString(self.cr1)
      oprot.writeFieldEnd()
    if self.cr2 is not None:
      oprot.writeFieldBegin('cr2', TType.STRING, 2)
      oprot.writeString(self.cr2)
      oprot.writeFieldEnd()
    if self.flag1 is not None:
      oprot.writeFieldBegin('flag1', TType.BOOL, 3)
      oprot.writeBool(self.flag1)
      oprot.writeFieldEnd()
    if self.ip is not None:
      oprot.writeFieldBegin('ip', TType.STRING, 4)
      oprot.writeString(self.ip)
      oprot.writeFieldEnd()
    if self.comname is not None:
      oprot.writeFieldBegin('comname', TType.STRING, 5)
      oprot.writeString(self.comname)
      oprot.writeFieldEnd()
    if self.val1 is not None:
      oprot.writeFieldBegin('val1', TType.I32, 6)
      oprot.writeI32(self.val1)
      oprot.writeFieldEnd()
    if self.cr5 is not None:
      oprot.writeFieldBegin('cr5', TType.STRING, 7)
      oprot.writeString(self.cr5)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class loginWithIdentityCredentialForCertificate_result:
  """
  Attributes:
   - success
  """

  thrift_spec = (
    (0, TType.STRUCT, 'success', (loginWithIdentityCredentialForCertificateResult, loginWithIdentityCredentialForCertificateResult.thrift_spec), None, ), # 0
  )

  def __init__(self, success=None,):
    self.success = success

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.STRUCT:
          self.success = loginWithIdentityCredentialForCertificateResult()
          self.success.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('loginWithIdentityCredentialForCertificate_result')
    if self.success is not None:
      oprot.writeFieldBegin('success', TType.STRUCT, 0)
      self.success.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class loginWithIdentityCredentialForCertificate2_args:
  """
  Attributes:
   - cr1
   - cr2
   - flag1
   - ip
   - comname
   - val1
   - cr5
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'cr1', None, None, ), # 1
    (2, TType.STRING, 'cr2', None, None, ), # 2
    (3, TType.BOOL, 'flag1', None, None, ), # 3
    (4, TType.STRING, 'ip', None, None, ), # 4
    (5, TType.STRING, 'comname', None, None, ), # 5
    (6, TType.I32, 'val1', None, None, ), # 6
    (7, TType.STRING, 'cr5', None, None, ), # 7
  )

  def __init__(self, cr1=None, cr2=None, flag1=None, ip=None, comname=None, val1=None, cr5=None,):
    self.cr1 = cr1
    self.cr2 = cr2
    self.flag1 = flag1
    self.ip = ip
    self.comname = comname
    self.val1 = val1
    self.cr5 = cr5

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.cr1 = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.cr2 = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.BOOL:
          self.flag1 = iprot.readBool();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.ip = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.STRING:
          self.comname = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.I32:
          self.val1 = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.STRING:
          self.cr5 = iprot.readString();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('loginWithIdentityCredentialForCertificate2_args')
    if self.cr1 is not None:
      oprot.writeFieldBegin('cr1', TType.STRING, 1)
      oprot.writeString(self.cr1)
      oprot.writeFieldEnd()
    if self.cr2 is not None:
      oprot.writeFieldBegin('cr2', TType.STRING, 2)
      oprot.writeString(self.cr2)
      oprot.writeFieldEnd()
    if self.flag1 is not None:
      oprot.writeFieldBegin('flag1', TType.BOOL, 3)
      oprot.writeBool(self.flag1)
      oprot.writeFieldEnd()
    if self.ip is not None:
      oprot.writeFieldBegin('ip', TType.STRING, 4)
      oprot.writeString(self.ip)
      oprot.writeFieldEnd()
    if self.comname is not None:
      oprot.writeFieldBegin('comname', TType.STRING, 5)
      oprot.writeString(self.comname)
      oprot.writeFieldEnd()
    if self.val1 is not None:
      oprot.writeFieldBegin('val1', TType.I32, 6)
      oprot.writeI32(self.val1)
      oprot.writeFieldEnd()
    if self.cr5 is not None:
      oprot.writeFieldBegin('cr5', TType.STRING, 7)
      oprot.writeString(self.cr5)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class loginWithIdentityCredentialForCertificate2_result:
  """
  Attributes:
   - success
  """

  thrift_spec = (
    (0, TType.STRUCT, 'success', (loginWithIdentityCredentialForCertificateResult2, loginWithIdentityCredentialForCertificateResult2.thrift_spec), None, ), # 0
  )

  def __init__(self, success=None,):
    self.success = success

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.STRUCT:
          self.success = loginWithIdentityCredentialForCertificateResult2()
          self.success.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('loginWithIdentityCredentialForCertificate2_result')
    if self.success is not None:
      oprot.writeFieldBegin('success', TType.STRUCT, 0)
      self.success.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
